/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.movie.GUI;
import com.mycompany.movie.CLI.Manager;
import com.mycompany.movie.Movies.Movie;
import com.mycompany.movie.Movies.MovieLibrary;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author MU
 */
public class DeleteMovie extends JFrame {

    /**
     * Creates new form DeleteMovie
     */
    public DeleteMovie() {
        initComponents();
        Manager.initializeLibrary();
        for (Movie movie : MovieLibrary.getMovies()) {
                    Movielist.addItem(movie.getTitle());
               }

         redo.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
               MainMenu11 main = new MainMenu11();
               main.show();
               dispose();
           }   
           });
          Delete.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
                Movie x =  (Movie) Movielist.getSelectedItem();
                if(Movielist.getItemCount() == 0){
                    output.setName("You have to chosse at least one Movie !");
                }
                if(MovieLibrary.getMovies().isEmpty()){
                    output.setName("No Movies in MovieLibrary !"); 
                }
                Movie movieToDelete = null;
                for (Movie movie : MovieLibrary.getMovies()) {
                if (movie.getTitle().equals(x)) {
                    movieToDelete = movie;
                    break;
                }
                }
                if (movieToDelete != null && MovieLibrary.deleteMovie(movieToDelete)) {
                output.setName(x + " has been deleted successfully.");
                Movielist.removeItem(x); // إزالة العنوان من القائمة
                } else {
                    output.setName("Something went wrong. Cannot delete this movie.");
                }
//                if(MovieLibrary.deleteMovie(x)){
//                    output.setName(x+" has been deleted Successfully.");
//                }else{
//                    output.setName("something wrong cannot Delete this movie.");
//                }
           }   
           });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redo = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Movielist = new javax.swing.JComboBox<>();
        output = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        redo.setBackground(new java.awt.Color(51, 153, 255));
        redo.setForeground(new java.awt.Color(255, 255, 255));
        redo.setText("Back");
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });

        Delete.setText("Delete Movie");

        output.setText("Output :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Movielist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(redo)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Movielist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redo)
                    .addComponent(Delete)
                    .addComponent(output))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JComboBox<String> Movielist;
    private javax.swing.JLabel output;
    private javax.swing.JButton redo;
    // End of variables declaration//GEN-END:variables
}
